version: '3.9'

services:
  db:
    image: postgres:12-buster
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  redisqueue:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
